/**
 * `thread/fork` — branch a thread. We clone the parent ThreadMeta, generate
 * a new threadId, and copy the parent's transcript so the SDK's resume path
 * picks up history on the next turn. The fork inherits model/sandbox/etc.
 * unless the request overrides them (we accept the same fields as
 * thread/start).
 *
 * codex's protocol allows `excludeTurns: true` to fork without replaying
 * history. We honor that by skipping the transcript copy.
 */

import { promises as fs } from "node:fs";
import { randomUUID } from "node:crypto";

import {
  isJsonObject,
  RPC_INVALID_PARAMS,
  type JsonValue,
  type Thread,
  type ThreadForkParams,
  type ThreadStartResponse,
} from "../protocol.js";
import { RpcError } from "../server.js";
import type { ThreadStore } from "../thread-store.js";
import type { Logger } from "../transport.js";
import { validateOutbound } from "../validators.js";

const THREAD_NOT_FOUND_CODE = -32004;

export function createThreadForkHandler(threadStore: ThreadStore, logger: Logger) {
  return async function handleThreadFork(rawParams: JsonValue | undefined): Promise<JsonValue> {
    const params = parseParams(rawParams);
    const parent = await threadStore.readMeta(params.threadId);
    if (!parent) {
      throw new RpcError(THREAD_NOT_FOUND_CODE, `Thread not found: ${params.threadId}`);
    }

    const newThreadId = randomUUID();
    const nowSec = Math.floor(Date.now() / 1000);

    const fork = await threadStore.createThread({
      cwd: typeof params.cwd === "string" ? params.cwd : parent.cwd,
      model: typeof params.model === "string" ? params.model : parent.model,
      modelProvider:
        typeof params.modelProvider === "string" ? params.modelProvider : parent.modelProvider,
      approvalPolicy: parent.approvalPolicy,
      approvalsReviewer: parent.approvalsReviewer,
      sandbox: parent.sandbox,
      serviceTier: parent.serviceTier ?? null,
      developerInstructions:
        typeof params.baseInstructions === "string"
          ? params.baseInstructions
          : parent.developerInstructions,
      dynamicTools: parent.dynamicTools,
      mcpServersConfig: parent.mcpServersConfig,
      forkedFromId: parent.id,
      cliVersion: parent.cliVersion,
    });

    // The fork's id was just generated by createThread; we want the caller-
    // chosen newThreadId to take precedence so external systems referencing
    // a specific id still work. Update the meta to use newThreadId.
    if (fork.id !== newThreadId) {
      // The store already wrote meta.json under its generated id. We could
      // rename, but the simpler approach is to just adopt the generated id
      // and return that; codex clients use the response's thread.id anyway.
    }

    if (!params.excludeTurns) {
      // Copy the parent transcript so SDK resume sees prior history.
      try {
        await fs.copyFile(
          threadStore.messagesPath(parent.id),
          threadStore.messagesPath(fork.id),
        );
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
          logger.warn("[thread/fork] transcript copy failed; fork will start fresh", {
            parentId: parent.id,
            forkId: fork.id,
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }
    }

    const thread: Thread = {
      id: fork.id,
      sessionId: fork.sessionId,
      cliVersion: fork.cliVersion,
      createdAt: fork.createdAt,
      updatedAt: fork.updatedAt,
      cwd: fork.cwd,
      ephemeral: typeof params.ephemeral === "boolean" ? params.ephemeral : false,
      modelProvider: fork.modelProvider,
      preview: "",
      source: fork.source,
      status: { type: "idle" },
      turns: [],
      forkedFromId: parent.id,
    };

    const response: ThreadStartResponse = {
      thread,
      model: fork.model,
      modelProvider: fork.modelProvider,
      cwd: fork.cwd,
      approvalPolicy: fork.approvalPolicy,
      approvalsReviewer: fork.approvalsReviewer,
      sandbox: fork.sandbox,
      serviceTier: fork.serviceTier ?? null,
      instructionSources: [],
      runtimeWorkspaceRoots: [],
    };

    // thread/fork validates against the same schema as thread/start.
    validateOutbound("threadStart", response, logger);
    logger.info("[thread/fork] forked", {
      parentId: parent.id,
      forkId: fork.id,
      excludeTurns: Boolean(params.excludeTurns),
    });
    return response as unknown as JsonValue;
  };
}

function parseParams(raw: JsonValue | undefined): ThreadForkParams {
  if (!isJsonObject(raw) || typeof raw.threadId !== "string") {
    throw new RpcError(RPC_INVALID_PARAMS, "thread/fork requires { threadId: string, ... }");
  }
  return raw as ThreadForkParams;
}
