/**
 * `thread/fork` — branch a thread. We clone the parent ThreadMeta, generate
 * a new threadId, and copy the parent's transcript so the SDK's resume path
 * picks up history on the next turn. The fork inherits model/sandbox/etc.
 * unless the request overrides them (we accept the same fields as
 * thread/start).
 *
 * codex's protocol allows `excludeTurns: true` to fork without replaying
 * history. We honor that by skipping the transcript copy.
 */

import { promises as fs } from "node:fs";
import { randomUUID } from "node:crypto";

import {
  isJsonObject,
  RPC_INVALID_PARAMS,
  type AskForApproval,
  type DynamicToolSpec,
  type JsonValue,
  type SandboxPolicyResponse,
  type Thread,
  type ThreadForkParams,
  type ThreadStartResponse,
} from "../protocol.js";
import { RpcError } from "../server.js";
import type { ThreadStore } from "../thread-store.js";
import type { Logger } from "../transport.js";
import { validateOutbound } from "../validators.js";

const THREAD_NOT_FOUND_CODE = -32004;

export function createThreadForkHandler(threadStore: ThreadStore, logger: Logger) {
  return async function handleThreadFork(rawParams: JsonValue | undefined): Promise<JsonValue> {
    const params = parseParams(rawParams);
    const parent = await threadStore.readMeta(params.threadId);
    if (!parent) {
      throw new RpcError(THREAD_NOT_FOUND_CODE, `Thread not found: ${params.threadId}`);
    }

    const newThreadId = randomUUID();
    const nowSec = Math.floor(Date.now() / 1000);

    // The bridge uses thread/fork specifically when the dynamic-tool
    // catalog changed mid-session: the goal is to preserve transcript
    // continuity (handled by the messages.jsonl copy below) while
    // adopting both the new tool set AND the current openclaw
    // execution-policy envelope (approvalPolicy, sandbox, disallowedTools).
    // Honoring per-field overrides matters because without it the fork
    // inherits the parent's stale approval/sandbox posture even after
    // the user's openclaw config changed mid-session. Each field that
    // accepts an override falls back to parent inheritance only when
    // the bridge omits it — so codex-style branch-without-catalog-change
    // callers still get parent inheritance.
    const dynamicToolsOverride = isCatalogOverride(params.dynamicTools)
      ? normalizeDynamicTools(params.dynamicTools)
      : undefined;
    const mcpServersOverride = isJsonObject(params.mcpServersConfig)
      ? params.mcpServersConfig
      : undefined;
    const approvalPolicyOverride = readApprovalPolicyOverride(params.approvalPolicy);
    const sandboxOverride = readSandboxOverride(params.sandbox);
    const disallowedToolsOverride = readDisallowedToolsOverride(params.disallowedTools);
    const fork = await threadStore.createThread({
      cwd: typeof params.cwd === "string" ? params.cwd : parent.cwd,
      model: typeof params.model === "string" ? params.model : parent.model,
      modelProvider:
        typeof params.modelProvider === "string" ? params.modelProvider : parent.modelProvider,
      approvalPolicy: approvalPolicyOverride ?? parent.approvalPolicy,
      approvalsReviewer: parent.approvalsReviewer,
      sandbox: sandboxOverride ?? parent.sandbox,
      serviceTier: parent.serviceTier ?? null,
      developerInstructions:
        typeof params.baseInstructions === "string"
          ? params.baseInstructions
          : parent.developerInstructions,
      dynamicTools: dynamicToolsOverride ?? parent.dynamicTools,
      dynamicToolsFingerprint:
        typeof params.dynamicToolsFingerprint === "string"
          ? params.dynamicToolsFingerprint
          : parent.dynamicToolsFingerprint,
      mcpServersConfig: mcpServersOverride ?? parent.mcpServersConfig,
      ...(disallowedToolsOverride !== undefined
        ? { disallowedTools: disallowedToolsOverride }
        : parent.disallowedTools !== undefined
          ? { disallowedTools: parent.disallowedTools }
          : {}),
      forkedFromId: parent.id,
      cliVersion: parent.cliVersion,
    });

    // The fork's id was just generated by createThread; we want the caller-
    // chosen newThreadId to take precedence so external systems referencing
    // a specific id still work. Update the meta to use newThreadId.
    if (fork.id !== newThreadId) {
      // The store already wrote meta.json under its generated id. We could
      // rename, but the simpler approach is to just adopt the generated id
      // and return that; codex clients use the response's thread.id anyway.
    }

    if (!params.excludeTurns) {
      // Copy the parent transcript so SDK resume sees prior history.
      try {
        await fs.copyFile(
          threadStore.messagesPath(parent.id),
          threadStore.messagesPath(fork.id),
        );
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
          logger.warn("[thread/fork] transcript copy failed; fork will start fresh", {
            parentId: parent.id,
            forkId: fork.id,
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }
    }

    const thread: Thread = {
      id: fork.id,
      sessionId: fork.sessionId,
      cliVersion: fork.cliVersion,
      createdAt: fork.createdAt,
      updatedAt: fork.updatedAt,
      cwd: fork.cwd,
      ephemeral: typeof params.ephemeral === "boolean" ? params.ephemeral : false,
      modelProvider: fork.modelProvider,
      preview: "",
      source: fork.source,
      status: { type: "idle" },
      turns: [],
      forkedFromId: parent.id,
      name: null,
    };

    const response: ThreadStartResponse = {
      thread,
      model: fork.model,
      modelProvider: fork.modelProvider,
      cwd: fork.cwd,
      approvalPolicy: fork.approvalPolicy,
      approvalsReviewer: fork.approvalsReviewer,
      sandbox: fork.sandbox,
      serviceTier: fork.serviceTier ?? null,
      instructionSources: [],
      runtimeWorkspaceRoots: [],
    };

    // thread/fork validates against the same schema as thread/start.
    validateOutbound("threadStart", response, logger);
    logger.info("[thread/fork] forked", {
      parentId: parent.id,
      forkId: fork.id,
      excludeTurns: Boolean(params.excludeTurns),
    });
    return response as unknown as JsonValue;
  };
}

function parseParams(raw: JsonValue | undefined): ThreadForkParams {
  if (!isJsonObject(raw) || typeof raw.threadId !== "string") {
    throw new RpcError(RPC_INVALID_PARAMS, "thread/fork requires { threadId: string, ... }");
  }
  return raw as ThreadForkParams;
}

function isCatalogOverride(value: unknown): value is unknown[] {
  return Array.isArray(value);
}

const APPROVAL_POLICY_STRINGS = new Set(["untrusted", "on-failure", "on-request", "never"]);

function readApprovalPolicyOverride(raw: unknown): AskForApproval | undefined {
  if (typeof raw === "string" && APPROVAL_POLICY_STRINGS.has(raw)) {
    return raw as AskForApproval;
  }
  if (isJsonObject(raw) && isJsonObject(raw.granular)) {
    return raw as unknown as AskForApproval;
  }
  return undefined;
}

function readSandboxOverride(raw: unknown): SandboxPolicyResponse | undefined {
  if (isJsonObject(raw) && typeof raw.type === "string") {
    return raw as unknown as SandboxPolicyResponse;
  }
  if (typeof raw === "string") {
    return { type: raw };
  }
  return undefined;
}

function readDisallowedToolsOverride(raw: unknown): string[] | undefined {
  if (!Array.isArray(raw)) {
    return undefined;
  }
  return raw.filter((entry): entry is string => typeof entry === "string");
}

function normalizeDynamicTools(raw: unknown): DynamicToolSpec[] {
  if (!Array.isArray(raw)) return [];
  const out: DynamicToolSpec[] = [];
  for (const t of raw) {
    if (
      t &&
      typeof t === "object" &&
      typeof (t as { name?: unknown }).name === "string" &&
      typeof (t as { description?: unknown }).description === "string"
    ) {
      out.push(t as DynamicToolSpec);
    }
  }
  return out;
}
